// Generated by Supabase (project ibmzunowmqpdrnikthrc). Do not edit by hand.
// Regenerate after migrations with the Supabase types generator.
/* eslint-disable */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      attachments: {
        Row: {
          bucket: string
          byte_size: number | null
          company_id: string | null
          content_type: string | null
          created_at: string
          deleted_at: string | null
          filename: string
          id: string
          metadata: Json
          owner_user_id: string | null
          path: string
          realm_id: string
          subsystem: string | null
          updated_at: string
        }
        Insert: {
          bucket: string
          byte_size?: number | null
          company_id?: string | null
          content_type?: string | null
          created_at?: string
          deleted_at?: string | null
          filename: string
          id?: string
          metadata?: Json
          owner_user_id?: string | null
          path: string
          realm_id: string
          subsystem?: string | null
          updated_at?: string
        }
        Update: {
          bucket?: string
          byte_size?: number | null
          company_id?: string | null
          content_type?: string | null
          created_at?: string
          deleted_at?: string | null
          filename?: string
          id?: string
          metadata?: Json
          owner_user_id?: string | null
          path?: string
          realm_id?: string
          subsystem?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "attachments_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attachments_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attachments_realm_id_fkey"
            columns: ["realm_id"]
            isOneToOne: false
            referencedRelation: "realms"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_events: {
        Row: {
          action: string
          actor_user_id: string | null
          after: Json | null
          before: Json | null
          company_id: string | null
          created_at: string
          device: string | null
          id: string
          ip: unknown
          realm_id: string | null
          subsystem: string | null
          target_id: string | null
          target_table: string | null
        }
        Insert: {
          action: string
          actor_user_id?: string | null
          after?: Json | null
          before?: Json | null
          company_id?: string | null
          created_at?: string
          device?: string | null
          id?: string
          ip?: unknown
          realm_id?: string | null
          subsystem?: string | null
          target_id?: string | null
          target_table?: string | null
        }
        Update: {
          action?: string
          actor_user_id?: string | null
          after?: Json | null
          before?: Json | null
          company_id?: string | null
          created_at?: string
          device?: string | null
          id?: string
          ip?: unknown
          realm_id?: string | null
          subsystem?: string | null
          target_id?: string | null
          target_table?: string | null
        }
        Relationships: []
      }
      companies: {
        Row: {
          created_at: string
          currency: string
          deleted_at: string | null
          id: string
          kind: string
          metadata: Json
          name: string
          parent_company_id: string | null
          realm_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          currency?: string
          deleted_at?: string | null
          id?: string
          kind?: string
          metadata?: Json
          name: string
          parent_company_id?: string | null
          realm_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          currency?: string
          deleted_at?: string | null
          id?: string
          kind?: string
          metadata?: Json
          name?: string
          parent_company_id?: string | null
          realm_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "companies_parent_company_id_fkey"
            columns: ["parent_company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "companies_realm_id_fkey"
            columns: ["realm_id"]
            isOneToOne: false
            referencedRelation: "realms"
            referencedColumns: ["id"]
          },
        ]
      }
      memberships: {
        Row: {
          company_id: string | null
          created_at: string
          deleted_at: string | null
          ends_at: string | null
          id: string
          is_sovereign: boolean
          realm_id: string
          scope: string
          starts_at: string | null
          status: string
          title_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          company_id?: string | null
          created_at?: string
          deleted_at?: string | null
          ends_at?: string | null
          id?: string
          is_sovereign?: boolean
          realm_id: string
          scope?: string
          starts_at?: string | null
          status?: string
          title_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          company_id?: string | null
          created_at?: string
          deleted_at?: string | null
          ends_at?: string | null
          id?: string
          is_sovereign?: boolean
          realm_id?: string
          scope?: string
          starts_at?: string | null
          status?: string
          title_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memberships_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_realm_id_fkey"
            columns: ["realm_id"]
            isOneToOne: false
            referencedRelation: "realms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_title_id_fkey"
            columns: ["title_id"]
            isOneToOne: false
            referencedRelation: "titles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          channel: string
          created_at: string
          id: string
          kind: string
          payload: Json
          priority: string
          read_at: string | null
          realm_id: string
          recipient_user_id: string
          subsystem: string | null
          title: string
        }
        Insert: {
          body?: string | null
          channel?: string
          created_at?: string
          id?: string
          kind: string
          payload?: Json
          priority?: string
          read_at?: string | null
          realm_id: string
          recipient_user_id: string
          subsystem?: string | null
          title: string
        }
        Update: {
          body?: string | null
          channel?: string
          created_at?: string
          id?: string
          kind?: string
          payload?: Json
          priority?: string
          read_at?: string | null
          realm_id?: string
          recipient_user_id?: string
          subsystem?: string | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_realm_id_fkey"
            columns: ["realm_id"]
            isOneToOne: false
            referencedRelation: "realms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_recipient_user_id_fkey"
            columns: ["recipient_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      permission_grants: {
        Row: {
          action: string
          authority_currency: string | null
          authority_limit: number | null
          created_at: string
          effect: string
          ends_at: string | null
          granted_by: string | null
          id: string
          membership_id: string
          realm_id: string
          reason: string | null
          starts_at: string
          subsystem: string
          updated_at: string
        }
        Insert: {
          action: string
          authority_currency?: string | null
          authority_limit?: number | null
          created_at?: string
          effect?: string
          ends_at?: string | null
          granted_by?: string | null
          id?: string
          membership_id: string
          realm_id: string
          reason?: string | null
          starts_at?: string
          subsystem: string
          updated_at?: string
        }
        Update: {
          action?: string
          authority_currency?: string | null
          authority_limit?: number | null
          created_at?: string
          effect?: string
          ends_at?: string | null
          granted_by?: string | null
          id?: string
          membership_id?: string
          realm_id?: string
          reason?: string | null
          starts_at?: string
          subsystem?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "permission_grants_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "permission_grants_membership_id_fkey"
            columns: ["membership_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "permission_grants_realm_id_fkey"
            columns: ["realm_id"]
            isOneToOne: false
            referencedRelation: "realms"
            referencedColumns: ["id"]
          },
        ]
      }
      realms: {
        Row: {
          brand: Json
          created_at: string
          data_residency: string
          deleted_at: string | null
          id: string
          name: string
          owner_user_id: string
          slug: string
          updated_at: string
        }
        Insert: {
          brand?: Json
          created_at?: string
          data_residency?: string
          deleted_at?: string | null
          id?: string
          name: string
          owner_user_id: string
          slug: string
          updated_at?: string
        }
        Update: {
          brand?: Json
          created_at?: string
          data_residency?: string
          deleted_at?: string | null
          id?: string
          name?: string
          owner_user_id?: string
          slug?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "realms_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      title_permissions: {
        Row: {
          action: string
          allowed: boolean
          id: string
          realm_id: string
          subsystem: string
          title_id: string
        }
        Insert: {
          action: string
          allowed?: boolean
          id?: string
          realm_id: string
          subsystem: string
          title_id: string
        }
        Update: {
          action?: string
          allowed?: boolean
          id?: string
          realm_id?: string
          subsystem?: string
          title_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "title_permissions_realm_id_fkey"
            columns: ["realm_id"]
            isOneToOne: false
            referencedRelation: "realms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "title_permissions_title_id_fkey"
            columns: ["title_id"]
            isOneToOne: false
            referencedRelation: "titles"
            referencedColumns: ["id"]
          },
        ]
      }
      titles: {
        Row: {
          created_at: string
          deleted_at: string | null
          description: string | null
          id: string
          is_system: boolean
          key: string | null
          name: string
          realm_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          id?: string
          is_system?: boolean
          key?: string | null
          name: string
          realm_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          id?: string
          is_system?: boolean
          key?: string | null
          name?: string
          realm_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "titles_realm_id_fkey"
            columns: ["realm_id"]
            isOneToOne: false
            referencedRelation: "realms"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          deleted_at: string | null
          email: string | null
          full_name: string | null
          id: string
          locale: string
          phone: string | null
          reachability: Json
          timezone: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          email?: string | null
          full_name?: string | null
          id: string
          locale?: string
          phone?: string | null
          reachability?: Json
          timezone?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          email?: string | null
          full_name?: string | null
          id?: string
          locale?: string
          phone?: string | null
          reachability?: Json
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      rajask_authority_limit: {
        Args: {
          p_action: string
          p_company: string
          p_realm: string
          p_subsystem: string
        }
        Returns: number
      }
      rajask_bundle_actions: { Args: { p_bundle: string }; Returns: string[] }
      rajask_can_see_company: { Args: { p_company: string }; Returns: boolean }
      rajask_create_realm: {
        Args: { p_name: string; p_slug: string }
        Returns: string
      }
      rajask_has_permission: {
        Args: {
          p_action: string
          p_company: string
          p_realm: string
          p_subsystem: string
        }
        Returns: boolean
      }
      rajask_is_realm_member: { Args: { p_realm: string }; Returns: boolean }
      rajask_is_sovereign: { Args: { p_realm: string }; Returns: boolean }
      rajask_shares_realm: { Args: { p_other: string }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
