// Generated by Supabase (project ibmzunowmqpdrnikthrc). Do not edit by hand.
// Regenerate after migrations with the Supabase types generator.
/* eslint-disable */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      attachments: {
        Row: {
          bucket: string
          byte_size: number | null
          company_id: string | null
          content_type: string | null
          created_at: string
          deleted_at: string | null
          filename: string
          id: string
          metadata: Json
          owner_user_id: string | null
          path: string
          realm_id: string
          subsystem: string | null
          updated_at: string
        }
        Insert: {
          bucket: string
          byte_size?: number | null
          company_id?: string | null
          content_type?: string | null
          created_at?: string
          deleted_at?: string | null
          filename: string
          id?: string
          metadata?: Json
          owner_user_id?: string | null
          path: string
          realm_id: string
          subsystem?: string | null
          updated_at?: string
        }
        Update: {
          bucket?: string
          byte_size?: number | null
          company_id?: string | null
          content_type?: string | null
          created_at?: string
          deleted_at?: string | null
          filename?: string
          id?: string
          metadata?: Json
          owner_user_id?: string | null
          path?: string
          realm_id?: string
          subsystem?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      audit_events: {
        Row: {
          action: string
          actor_user_id: string | null
          after: Json | null
          before: Json | null
          company_id: string | null
          created_at: string
          device: string | null
          id: string
          ip: unknown
          realm_id: string | null
          subsystem: string | null
          target_id: string | null
          target_table: string | null
        }
        Insert: {
          action: string
          actor_user_id?: string | null
          after?: Json | null
          before?: Json | null
          company_id?: string | null
          created_at?: string
          device?: string | null
          id?: string
          ip?: unknown
          realm_id?: string | null
          subsystem?: string | null
          target_id?: string | null
          target_table?: string | null
        }
        Update: {
          action?: string
          actor_user_id?: string | null
          after?: Json | null
          before?: Json | null
          company_id?: string | null
          created_at?: string
          device?: string | null
          id?: string
          ip?: unknown
          realm_id?: string | null
          subsystem?: string | null
          target_id?: string | null
          target_table?: string | null
        }
        Relationships: []
      }
      companies: {
        Row: {
          created_at: string
          currency: string
          deleted_at: string | null
          id: string
          kind: string
          metadata: Json
          name: string
          parent_company_id: string | null
          realm_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          currency?: string
          deleted_at?: string | null
          id?: string
          kind?: string
          metadata?: Json
          name: string
          parent_company_id?: string | null
          realm_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          currency?: string
          deleted_at?: string | null
          id?: string
          kind?: string
          metadata?: Json
          name?: string
          parent_company_id?: string | null
          realm_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      conversation_members: {
        Row: {
          conversation_id: string
          created_at: string
          id: string
          joined_at: string
          last_read_at: string | null
          muted_until: string | null
          notifications_pref: string
          pinned: boolean
          realm_id: string
          role: string
          updated_at: string
          user_id: string
        }
        Insert: {
          conversation_id: string
          created_at?: string
          id?: string
          joined_at?: string
          last_read_at?: string | null
          muted_until?: string | null
          notifications_pref?: string
          pinned?: boolean
          realm_id: string
          role?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          conversation_id?: string
          created_at?: string
          id?: string
          joined_at?: string
          last_read_at?: string | null
          muted_until?: string | null
          notifications_pref?: string
          pinned?: boolean
          realm_id?: string
          role?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      conversations: {
        Row: {
          company_id: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          is_archived: boolean
          kind: string
          last_message_at: string | null
          name: string | null
          realm_id: string
          topic: string | null
          updated_at: string
        }
        Insert: {
          company_id?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          is_archived?: boolean
          kind?: string
          last_message_at?: string | null
          name?: string | null
          realm_id: string
          topic?: string | null
          updated_at?: string
        }
        Update: {
          company_id?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          is_archived?: boolean
          kind?: string
          last_message_at?: string | null
          name?: string | null
          realm_id?: string
          topic?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      invitations: {
        Row: {
          accepted_at: string | null
          accepted_by: string | null
          channel: string
          company_id: string | null
          created_at: string
          email: string | null
          expires_at: string
          id: string
          invited_by: string | null
          note: string | null
          opened_at: string | null
          phone: string | null
          realm_id: string
          scope: string
          status: string
          title_id: string
          token: string
          updated_at: string
        }
        Insert: {
          accepted_at?: string | null
          accepted_by?: string | null
          channel?: string
          company_id?: string | null
          created_at?: string
          email?: string | null
          expires_at?: string
          id?: string
          invited_by?: string | null
          note?: string | null
          opened_at?: string | null
          phone?: string | null
          realm_id: string
          scope?: string
          status?: string
          title_id: string
          token?: string
          updated_at?: string
        }
        Update: {
          accepted_at?: string | null
          accepted_by?: string | null
          channel?: string
          company_id?: string | null
          created_at?: string
          email?: string | null
          expires_at?: string
          id?: string
          invited_by?: string | null
          note?: string | null
          opened_at?: string | null
          phone?: string | null
          realm_id?: string
          scope?: string
          status?: string
          title_id?: string
          token?: string
          updated_at?: string
        }
        Relationships: []
      }
      memberships: {
        Row: {
          company_id: string | null
          created_at: string
          deleted_at: string | null
          ends_at: string | null
          id: string
          is_sovereign: boolean
          realm_id: string
          scope: string
          starts_at: string | null
          status: string
          title_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          company_id?: string | null
          created_at?: string
          deleted_at?: string | null
          ends_at?: string | null
          id?: string
          is_sovereign?: boolean
          realm_id: string
          scope?: string
          starts_at?: string | null
          status?: string
          title_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          company_id?: string | null
          created_at?: string
          deleted_at?: string | null
          ends_at?: string | null
          id?: string
          is_sovereign?: boolean
          realm_id?: string
          scope?: string
          starts_at?: string | null
          status?: string
          title_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      message_reactions: {
        Row: {
          created_at: string
          emoji: string
          id: string
          message_id: string
          realm_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          emoji: string
          id?: string
          message_id: string
          realm_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          emoji?: string
          id?: string
          message_id?: string
          realm_id?: string
          user_id?: string
        }
        Relationships: []
      }
      messages: {
        Row: {
          body: string | null
          conversation_id: string
          created_at: string
          edited_at: string | null
          id: string
          kind: string
          metadata: Json
          realm_id: string
          recalled_at: string | null
          reply_to_id: string | null
          sender_user_id: string | null
        }
        Insert: {
          body?: string | null
          conversation_id: string
          created_at?: string
          edited_at?: string | null
          id?: string
          kind?: string
          metadata?: Json
          realm_id: string
          recalled_at?: string | null
          reply_to_id?: string | null
          sender_user_id?: string | null
        }
        Update: {
          body?: string | null
          conversation_id?: string
          created_at?: string
          edited_at?: string | null
          id?: string
          kind?: string
          metadata?: Json
          realm_id?: string
          recalled_at?: string | null
          reply_to_id?: string | null
          sender_user_id?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string | null
          channel: string
          created_at: string
          id: string
          kind: string
          payload: Json
          priority: string
          read_at: string | null
          realm_id: string
          recipient_user_id: string
          subsystem: string | null
          title: string
        }
        Insert: {
          body?: string | null
          channel?: string
          created_at?: string
          id?: string
          kind: string
          payload?: Json
          priority?: string
          read_at?: string | null
          realm_id: string
          recipient_user_id: string
          subsystem?: string | null
          title: string
        }
        Update: {
          body?: string | null
          channel?: string
          created_at?: string
          id?: string
          kind?: string
          payload?: Json
          priority?: string
          read_at?: string | null
          realm_id?: string
          recipient_user_id?: string
          subsystem?: string | null
          title?: string
        }
        Relationships: []
      }
      permission_grants: {
        Row: {
          action: string
          authority_currency: string | null
          authority_limit: number | null
          created_at: string
          effect: string
          ends_at: string | null
          granted_by: string | null
          id: string
          membership_id: string
          realm_id: string
          reason: string | null
          starts_at: string
          subsystem: string
          updated_at: string
        }
        Insert: {
          action: string
          authority_currency?: string | null
          authority_limit?: number | null
          created_at?: string
          effect?: string
          ends_at?: string | null
          granted_by?: string | null
          id?: string
          membership_id: string
          realm_id: string
          reason?: string | null
          starts_at?: string
          subsystem: string
          updated_at?: string
        }
        Update: {
          action?: string
          authority_currency?: string | null
          authority_limit?: number | null
          created_at?: string
          effect?: string
          ends_at?: string | null
          granted_by?: string | null
          id?: string
          membership_id?: string
          realm_id?: string
          reason?: string | null
          starts_at?: string
          subsystem?: string
          updated_at?: string
        }
        Relationships: []
      }
      realms: {
        Row: {
          brand: Json
          created_at: string
          data_residency: string
          deleted_at: string | null
          id: string
          name: string
          owner_user_id: string
          slug: string
          updated_at: string
        }
        Insert: {
          brand?: Json
          created_at?: string
          data_residency?: string
          deleted_at?: string | null
          id?: string
          name: string
          owner_user_id: string
          slug: string
          updated_at?: string
        }
        Update: {
          brand?: Json
          created_at?: string
          data_residency?: string
          deleted_at?: string | null
          id?: string
          name?: string
          owner_user_id?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      title_permissions: {
        Row: {
          action: string
          allowed: boolean
          id: string
          realm_id: string
          subsystem: string
          title_id: string
        }
        Insert: {
          action: string
          allowed?: boolean
          id?: string
          realm_id: string
          subsystem: string
          title_id: string
        }
        Update: {
          action?: string
          allowed?: boolean
          id?: string
          realm_id?: string
          subsystem?: string
          title_id?: string
        }
        Relationships: []
      }
      titles: {
        Row: {
          created_at: string
          deleted_at: string | null
          description: string | null
          id: string
          is_system: boolean
          key: string | null
          name: string
          realm_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          id?: string
          is_system?: boolean
          key?: string | null
          name: string
          realm_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          id?: string
          is_system?: boolean
          key?: string | null
          name?: string
          realm_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      broadcasts: {
        Row: {
          body: string | null
          channels: string[]
          company_id: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          realm_id: string
          scheduled_at: string | null
          segment: Json
          sent_at: string | null
          status: string
          title: string
          updated_at: string
        }
        Insert: {
          body?: string | null
          channels?: string[]
          company_id?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          realm_id: string
          scheduled_at?: string | null
          segment?: Json
          sent_at?: string | null
          status?: string
          title: string
          updated_at?: string
        }
        Update: {
          body?: string | null
          channels?: string[]
          company_id?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          realm_id?: string
          scheduled_at?: string | null
          segment?: Json
          sent_at?: string | null
          status?: string
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      broadcast_receipts: {
        Row: {
          broadcast_id: string
          channel: string
          delivered_at: string
          id: string
          read_at: string | null
          realm_id: string
          user_id: string
        }
        Insert: {
          broadcast_id: string
          channel?: string
          delivered_at?: string
          id?: string
          read_at?: string | null
          realm_id: string
          user_id: string
        }
        Update: {
          broadcast_id?: string
          channel?: string
          delivered_at?: string
          id?: string
          read_at?: string | null
          realm_id?: string
          user_id?: string
        }
        Relationships: []
      }
      calendar_events: {
        Row: {
          all_day: boolean
          company_id: string | null
          created_at: string
          deleted_at: string | null
          description: string | null
          ends_at: string | null
          id: string
          kind: string
          location: string | null
          metadata: Json
          owner_user_id: string
          realm_id: string
          starts_at: string
          timezone: string
          title: string
          updated_at: string
          visibility: string
        }
        Insert: {
          all_day?: boolean
          company_id?: string | null
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          ends_at?: string | null
          id?: string
          kind?: string
          location?: string | null
          metadata?: Json
          owner_user_id: string
          realm_id: string
          starts_at: string
          timezone?: string
          title: string
          updated_at?: string
          visibility?: string
        }
        Update: {
          all_day?: boolean
          company_id?: string | null
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          ends_at?: string | null
          id?: string
          kind?: string
          location?: string | null
          metadata?: Json
          owner_user_id?: string
          realm_id?: string
          starts_at?: string
          timezone?: string
          title?: string
          updated_at?: string
          visibility?: string
        }
        Relationships: []
      }
      event_attendees: {
        Row: {
          created_at: string
          event_id: string
          id: string
          realm_id: string
          response: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          event_id: string
          id?: string
          realm_id: string
          response?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          event_id?: string
          id?: string
          realm_id?: string
          response?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          deleted_at: string | null
          email: string | null
          full_name: string | null
          id: string
          is_super_admin: boolean
          locale: string
          phone: string | null
          reachability: Json
          timezone: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          email?: string | null
          full_name?: string | null
          id: string
          is_super_admin?: boolean
          locale?: string
          phone?: string | null
          reachability?: Json
          timezone?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          email?: string | null
          full_name?: string | null
          id?: string
          is_super_admin?: boolean
          locale?: string
          phone?: string | null
          reachability?: Json
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      rajask_accept_invitation: { Args: { p_token: string }; Returns: string }
      rajask_authority_limit: {
        Args: {
          p_action: string
          p_company: string
          p_realm: string
          p_subsystem: string
        }
        Returns: number
      }
      rajask_bundle_actions: { Args: { p_bundle: string }; Returns: string[] }
      rajask_can_see_company: { Args: { p_company: string }; Returns: boolean }
      rajask_create_realm: {
        Args: { p_name: string; p_slug: string }
        Returns: string
      }
      rajask_get_or_create_dm: {
        Args: { p_other: string; p_realm: string }
        Returns: string
      }
      rajask_has_permission: {
        Args: {
          p_action: string
          p_company: string
          p_realm: string
          p_subsystem: string
        }
        Returns: boolean
      }
      rajask_in_conversation: { Args: { p_conv: string }; Returns: boolean }
      rajask_is_realm_member: { Args: { p_realm: string }; Returns: boolean }
      rajask_is_sovereign: { Args: { p_realm: string }; Returns: boolean }
      rajask_is_super_admin: { Args: Record<string, never>; Returns: boolean }
      rajask_send_broadcast: { Args: { p_broadcast: string }; Returns: number }
      rajask_open_invitation: {
        Args: { p_token: string }
        Returns: {
          expired: boolean
          realm_name: string
          status: string
          title_name: string
        }[]
      }
      rajask_shares_realm: { Args: { p_other: string }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
